---
title: "Porters 5 forces in Seventh Generation"
---

The industry that Seventh Generation is in is cleaning, paper, and personal care products, or more broadly, home care products. This industry is in the growth stage globally, 5% in 2016, and Seventh Generation is still growing as well. They have had double digit growth rates since 2006, and seem to be going strong. Many believe that Seventh Generation will continue to become more profitable under Unilever’s new leadership. It does seem like the industry is heading towards the shakeout stage; it will be interesting to see how the company handles the increased competitive intensity.  
As a company, Seventh Generation has an extremely strong set of values and mission that drives their decision making. They believe in making a positive impact that will affect the next seven generations. Their emphasis on the environment and transparency as well as building communities gives them competitive advantages and a loyal customer base.  



**Threat of new entrants**:
This industry has become more attractive to potential entrants, especially on the the green side of the home care product industry. The socially responsible and environmentally friendly consumer base is continuing to grow, and along with it are companies that are jumping on the green bandwagon. It is easy to add a green product to an already existing product line, so Seventh Generation is gaining some competition for its eco friendly consumers from existing home care companies. A good example of this is Green Works. This is an eco-friendly product line made by Clorox, a not so eco-friendly company. Tide even has a plant-based detergent called Tide purclean; another large company that is jumping on the green train. However, Seventh Generation is focused on being a good company as a whole, which gives them a competitive advantage over competitors like Clorox and Tide that have additional toxic product lines.  There are even more existing competitors in both the green industry and the not so green that Seventh Generation must contend with. 

**Rivalry among existing competitors**:
Since Seventh Generation is in a sub segment of the home care industry, it has competitors from both the “toxic” companies and the “green”. Their mission and values give them a unique competitive advantage, but they still must keep up with popular companies like Tide. When Tide pods came out and became a huge hit, Seventh generation had to rush to come up with a similar, but natural, product. They have had to wrestle with the high cleaning power of the harsh chemicals that other companies provided, searching for natural ingredients that could give the cleanliness that other companies provided. 
 Method is another green based company that has risen along with Seventh Generation, and is one of its biggest eco friendly competitors. They both have similar visions, to make the world “cleaner and greener”, and similar product lines. However, Method does not disclose the specific ingredients that are in their products. Since Seventh generation does, this gives them a competitive advantage when it comes to transparency.  Honest, Ecos, and Mrs. Meyers are also fairly large competitors in this eco friendly market. 
 
**Bargaining power of buyers**:
Because of products like Tide, consumers expect “clean” to have a smell. Really, clean should just smell like nothing. But, that “clean smell” is an expectation that Seventh Generation must break, as that smell typically comes along with unnatural ingredients. They have also made innovative technologies, like stronger products in smaller bottles, that consumers aren't ready for, because they are so different than the other products out there.  Consumers have a large array of products to choose from, and Seventh Gen’s price point turns away some who would rather pay less for their cleaning products. Seventh Generation does have a base of customers committed to their brand, and don't mind paying more for a non-toxic product. Green consumers aren't the only target market of Seventh Gen; those with sensitive skin and specific allergies are extremely bothered by cleaning products with harsh chemicals. These buyers turn to Seventh Generation for largely health-based reasons.   

**Bargaining power of suppliers**:
	The green market has grown, and with it suppliers that are either willing to go green or are completely green have also grown. However, there are still less environmentally friendly suppliers than suppliers that make cheaper and more toxic materials. This means these green suppliers have more bargaining power, as there are less suppliers available. Seventh Gen has very high standards for their suppliers, and they must go through extensive training and programs. The cost that it takes for the suppliers to meet the company’s demands is high, and Seventh Gen works with them extensively to convince and help them. They have what they call Supplier days, where they talk to their suppliers about what they can do to improve their plants and their operations. This raises the bar for their suppliers, but creates a reliable network for Seventh Generation. 

**Threat of substitute products or services**:
There are alternative ways to clean the home, especially if the consumer is eco friendly and looking for natural cleaning solutions. Baking soda, lemon juice, and different types of vinegars are products that have been used for cleaning long before Tide or any big cleaning names were heard of. These are basic, natural ingredients and products that appeal to those that are already looking for simple, green cleaning solutions. Consumers that go back to these basics would be a part of the valuable target market that Seventh Generation markets towards. A service that would possibly prevent the consumption of Seventh Generation or even other cleaning products would be a cleaning service. These are not currently widely popular, and the cleaners themselves would have cleaning products, but the actual homeowner may not. 
